---
- name: My First Ansible Playbook
  hosts: all
  become: yes   # Run tasks with sudo privileges
  tasks:

    - name: Ping all managed nodes
      ansible.builtin.ping:

    - name: Create a directory on remote nodes
      ansible.builtin.file:
        path: /tmp/test_dir
        state: directory

    - name: Create a text file inside that directory
      ansible.builtin.copy:
        dest: /tmp/test_dir/hello.txt
        content: "Hello from Ansible!\n"
